orbit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from avatar import urls as avatar

local_patterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('authentication.urls', namespace='authentication')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^event/', include('events.urls', namespace='events')),
    url(r'^page/', include('pages.urls', namespace='pages')),
    url(r'^project/', include('projects.urls', namespace='projects')),
]

third_party_patterns = [
    url(r'^avatar/', include(avatar)),
]

urlpatterns = local_patterns + third_party_patterns


def fourohfour(request):
    return render(request, '404.html', status=404)


handler404 = fourohfour

projects/urls.py
from django.conf.urls import url
from .views import (
    ProjectCreateView,
    ProjectDetailView,
    ProjectHistoryView,
    ProjectIndexView,
    ProjectUpdateView,
    TaskCreateView,
    TaskDetailView,
    TaskIndexView,
)

urlpatterns = [
    url(
        regex=r'^create/?$',
        view=ProjectCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/task/?$',
        view=TaskIndexView.as_view(),
        name='task_index'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/task/create/?$',
        view=TaskCreateView.as_view(),
        name='task_create'
    ),
    url(
        regex=r'^(?P<project_pk>[^/]+)/task/(?P<task_pk>[^/]+)/?$',
        view=TaskDetailView.as_view(),
        name='task_detail'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/update/?$',
        view=ProjectUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/history/?$',
        view=ProjectHistoryView.as_view(),
        name='history'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/?$',
        view=ProjectDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'',
        view=ProjectIndexView.as_view(),
        name='index'
    ),
]

projects/models.py
from django.db import models
from django.urls import reverse
from pages.models import BasePage


class Project(BasePage):
    code = models.CharField(max_length=5)
    deadline = models.DateTimeField(blank=True, null=True)

    to_do = 0
    in_progress = 1
    completed = 2
    columns = (
        (to_do, 'to_do'),
        (in_progress, 'in_progress'),
        (completed, 'completed'),
    )

    class Meta:
        unique_together = ('code', 'version')

    def get_absolute_url(self):
        return reverse('projects:detail', kwargs={'pk': self.pk})

    def get_absolute_history_url(self):
        return reverse('projects:history', kwargs={'pk': self.pk})

    def get_absolute_task_index_url(self):
        return reverse('projects:task_index', kwargs={'pk': self.pk})


class Task(BasePage):
    task_project = models.ForeignKey(Project)
    column = models.CharField(max_length=1, choices=Project.columns, default=0)

    def get_absolute_url(self):
        project_pk = self.task_project.pk
        task_pk = self.pk
        return reverse('projects:task_detail', kwargs={'project_pk': project_pk, 'task_pk': task_pk})

projects/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from pages.forms import PageForm
from .models import Project, Task
from django.db.models import Max


class ProjectForm(PageForm):

    class Meta:
        model = Project
        fields = [
            'title',
            'code',
            'content',
            'changelog',
        ]
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _("Title goes here..."),
            }),
            'code': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _("Project Code"),
            }),
            'changelog': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _("What did you change?"),
            }),
        }


class TaskForm(PageForm):

    def __init__(self, *args, **kwargs):
        self.project = kwargs.pop('project', None)
        super(TaskForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Task
        fields = [
            'title',
            'content',
            'changelog',
        ]
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _("Title goes here..."),
            }),
            'changelog': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _("What did you change?"),
            }),
        }

    def save(self, commit=True):
        task = super(TaskForm, self).save(commit=False)
        task.task_project = self.project
        if commit:
            task.save()
        return task

projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView
from pages.views import PageCreateView, PageDetailView, PageHistoryView, PageIndexView, PageUpdateView
from .forms import ProjectForm, TaskForm
from .models import Project, Task


class ProjectCreateView(PageCreateView):
    template_name = 'projects/form.html'
    model = Project
    form_class = ProjectForm


class ProjectDetailView(PageDetailView):
    template_name = 'projects/detail.html'
    model = Project


class ProjectHistoryView(PageHistoryView):
    model = Project


class ProjectIndexView(PageIndexView):
    template_name = 'projects/index.html'
    model = Project


class ProjectUpdateView(PageUpdateView):
    template_name = 'projects/form.html'
    model = Project
    form_class = ProjectForm


class TaskCreateView(PageCreateView):
    template_name = 'projects/tasks/form.html'
    model = Task
    form_class = TaskForm

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        if (self.request.method == 'POST'):
            form = form_class(**self.get_form_kwargs())
        else:
            form = form_class()
        return form

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        kwargs['project'] = get_object_or_404(Project, pk=self.kwargs['pk'])
        return kwargs

    def get_success_url(self, **kwargs):
        project_pk = self.kwargs.get('pk')
        return reverse('projects:task_detail', kwargs={'project_pk': project_pk, 'task_pk': self.object.pk})


class TaskDetailView(PageDetailView):
    template_name = 'projects/tasks/detail.html'
    model = Task

    def get_object(self):
        project_pk = self.kwargs.get('project_pk')
        project = get_object_or_404(Project, pk=project_pk)
        task_pk = self.kwargs.get('task_pk')
        return get_object_or_404(Task, task_project=project, pk=task_pk)


class TaskIndexView(PageDetailView):
    template_name = 'projects/tasks/index.html'
    model = Project

    def get_context_data(self, *args, **kwargs):
        context = super(TaskIndexView, self).get_context_data(*args, **kwargs)
        context['to_do'] = Task.objects.filter(task_project=self.object, column=Project.to_do)
        context['in_progress'] = Task.objects.filter(task_project=self.object, column=Project.in_progress)
        context['completed'] = Task.objects.filter(task_project=self.object, column=Project.completed)
        return context

templates/projects/board.html
{% extends "base_site.html" %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
  <div class="container">
    <div class="col-sm-6 col-xs-12">
      <a href="{{ object.get_absolute_url }}">
        <button class="btn btn-sm btn-default">
          <span><i class="fa fa-caret-left"></i></span>
          <span>Back To Project Overview</span>
        </button>
      </a>
    </div>
    <div class="col-sm-6 col-xs-12">
      <div class="pull-right">
        <a href="{% url 'projects:task_create' slug=object.slug %}">
          <button class="btn btn-sm btn-default">
            <span>New Task</span>
          </button>
        </a>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <span>To Do</span>
          <div class="pull-right">
            <a data-toggle="collapse" data-target="#collapse-to-do" aria-controls="collapse-to-do" aria-expanded="true">
              <i class="fa fa-chevron-up"></i>
            </a>
          </div>
        </div>
        <div class="panel-body collapse in" id="collapse-to-do">
          {% for task in to_do %}
            <a href="{{ task.get_absolute_url }}">
              <div class="panel panel-default">
                <div class="panel-heading">{{ task.title }}</div>
                <div class="panel-body">asdf</div>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <span>In Progress</span>
          <div class="pull-right">
            <a data-toggle="collapse" data-target="#collapse-in-progress" aria-controls="collapse-in-progress" aria-expanded="true">
              <i class="fa fa-chevron-up"></i>
            </a>
          </div>
        </div>
        <div class="panel-body collapse in" id="collapse-in-progress">
          {% for task in in_progress %}
            <a href="{{ task.get_absolute_url }}">
              <div class="panel panel-default">
                <div class="panel-heading">{{ task.title }}</div>
                <div class="panel-body">asdf</div>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <span>Completed</span>
          <div class="pull-right">
            <a data-toggle="collapse" data-target="#collapse-completed" aria-controls="collapse-completed" aria-expanded="true">
              <i class="fa fa-chevron-up"></i>
            </a>
          </div>
        </div>
        <div class="panel-body collapse in" id="collapse-completed">
          {% for task in completed %}
            <a href="{{ task.get_absolute_url }}">
              <div class="panel panel-default">
                <div class="panel-heading">{{ task.title }}</div>
                <div class="panel-body">asdf</div>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/projects/detail.html
{% extends "base_site.html" %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
  <div class="row">
    <div class="x_panel">
      <div class="x_title">
        <div>
          <h2>{{ object.title }}</h2>
        </div>
        <div class="btn-group pull-right">
          <a href="#">
            <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Trash">
              <i class="fa fa-trash"></i>
            </button>
          </a>
          <a href="#">
            <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Print">
              <i class="fa fa-print"></i>
            </button>
          </a>
          <a href="{{ object.get_absolute_history_url }}">
            <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="History">
              <i class="fa fa-history"></i>
            </button>
          </a>
          <a href="#">
            <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Tag">
              <i class="fa fa-tag"></i>
            </button>
          </a>
          <a href="{{ object.get_absolute_task_index_url }}">
            <button class="btn btn-sm btn-warning" type="button">
              <i class="fa fa-table"></i> Project Board
            </button>
          </a>
          {% if object.is_removed %}
            <a>
              <button class="btn btn-sm btn-primary disabled">
                <i class="fa fa-edit"></i> Update
              </button>
            </a>
          {% else %}
            <a href="{% url 'projects:update' pk=object.pk %}">
              <button class="btn btn-sm btn-primary">
                <i class="fa fa-edit"></i> Update
              </button>
            </a>
          {% endif %}
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        {{ object.content | safe }}
      </div>
    </div>
  </div>
{% endblock %}

templates/projects/form.html
{% extends "base_site.html" %}

{% block title %}
  {% if form.instance.id %}
    Edit Project
  {% else %}
    New Project
  {% endif %}
{% endblock %}

{% block javascripts %}
  {{ block.super }}
  {{ form.media }}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <form method="POST">
          {% csrf_token %}
          <div class="x_title">
            <div class="form-group">
              {{ form.title.errors }}
              {{ form.title }}
            </div>
          </div>
          <div class="x_content">
            <div class="form-group textarea_primary">
              {{ form.content.errors }}
              {{ form.content }}
            </div>
            <div class="clearfix"></div>
            <div class="form-group">
              <div class="input-group">
                {{ form.changelog }}
                <span class="input-group-btn">
                  <input type="submit" class="btn btn-default submit btn-unpad" value="Save"/>
                </span>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/projects/index.html
{% extends "base_site.html" %}

{% block title %}Projects{% endblock %}

{% block content %}
  <div>
    <div class="row">
      <div class="x_panel">
        <table class="table">
          <thead>
            <tr>
              <th>Project</th>
              <th>Deadline</th>
            </tr>
          </thead>
          <tbody>
            {% for project in object_list %}
              <tr>
                <td>
                  <div><a href="{{ project.get_absolute_url }}">{{ project.title }}</a></div>
                </td>
                <td>
                  {{ project.deadline }}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}