accounts/urls.py
from django.conf.urls import url
from .views import AccountDetailView, AccountUpdateView


urlpatterns = [
    url(
        regex=r'^(?P<pk>[^/]+)/?$',
        view=AccountDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/edit/?$',
        view=AccountUpdateView.as_view(),
        name='edit'
    ),
]

orbit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from avatar import urls as avatar

local_patterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('authentication.urls', namespace='authentication')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^event/', include('events.urls', namespace='events')),
    url(r'^page/', include('pages.urls', namespace='pages')),
    url(r'^project/', include('projects.urls', namespace='projects')),
]

third_party_patterns = [
    url(r'^avatar/', include(avatar)),
]

urlpatterns = local_patterns + third_party_patterns


def fourohfour(request):
    return render(request, '404.html', status=404)


handler404 = fourohfour

pages/urls.py
from django.conf.urls import url
from .views import PageDetailView, PageCreateView, PageUpdateView, PageHistoryView, PageIndexView

urlpatterns = [
    url(
        regex=r'^create/?$',
        view=PageCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/update/?$',
        view=PageUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/history/?$',
        view=PageHistoryView.as_view(),
        name='history'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/?$',
        view=PageDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'',
        view=PageIndexView.as_view(),
        name='index'
    ),
]

templates/pages/detail.html
{% extends "base_site.html" %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>
            {{ object.title }}
          </h2>
          <div class="btn-group pull-right">
            <a href="#">
              <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Trash">
                <i class="fa fa-trash"></i>
              </button>
            </a>
            <a href="#">
              <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Print">
                <i class="fa fa-print"></i>
              </button>
            </a>
            <a href="{{ object.get_absolute_history_url }}">
              <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="History">
                <i class="fa fa-history"></i>
              </button>
            </a>
            <a href="#">
              <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Tag">
                <i class="fa fa-tag"></i>
              </button>
            </a>
            {% if object.is_removed %}
              <a>
                <button class="btn btn-sm btn-primary disabled">
                  <i class="fa fa-edit"></i> Update
                </button>
              </a>
            {% else %}
              <a href="{% url 'pages:update' pk=object.pk %}">
                <button class="btn btn-sm btn-primary">
                  <i class="fa fa-edit"></i> Update
                </button>
              </a>
            {% endif %}
          </div>

          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          {{ object.content | safe }}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/form.html
{% extends "base_site.html" %}

{% block title %}
  {% if form.instance.id %}
    Edit Page
  {% else %}
    New Page
  {% endif %}
{% endblock title %}

{% block javascripts %}
  {{ block.super }}
  {{ form.media }}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <form method="POST">
          {% csrf_token %}
          <div class="x_title">
            <div class="col-xs-12">
              <div class="form-group">
                {{ form.title.errors }}
                {{ form.title }}
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="col-xs-12">
              <div class="form-group textarea_primary">
                {{ form.content.errors }}
                {{ form.content }}
              </div>
              <div class="clearfix"></div>
              <div class="form-group">
                <div class="input-group">
                  {{ form.changelog }}
                  <span class="input-group-btn">
                    <input type="submit" class="btn btn-default submit btn-unpad" value="Save"/>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/history.html
{% extends "base_site.html" %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
  <div>
    <div class="page-title">
      <div class="title_left">
        <h3>Page History</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <table class="table">
            <thead>
              <tr>
                <th class="col-xs-1 text-center">
                  <span>
                    <i class="fa fa-history" data-placement="top" data-toggle="tooltip" data-original-title="Version"></i>
                  </span>
                </th>
                <th class="col-xs-7">
                  <span>
                    Title
                  </span>
                </th>
                <th class="col-xs-4">
                  <span>
                    Changelog
                  </span>
                </th>
              </tr>
            </thead>
            <tbody>
              {% for page in object_list %}
                <tr>
                  <td class="text-center">
                    <div data-placement="left" data-toggle="tooltip" data-original-title="{{ page.creation_date }}">
                      {% if object.id == page.id %}
                        <b>
                          {{ page.version }}
                        </b>
                      {% else %}
                        {{ page.version }}
                      {% endif %}
                    </div>
                  </td>
                  <td>
                    <a href="{{ page.get_absolute_url }}">
                      {% if object.id == page.id %}
                        <b>
                          {{ page.title }}
                        </b>
                      {% else %}
                        {{ page.title }}
                      {% endif %}
                    </a>
                  </td>
                  <td>
                    {{ page.changelog }}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/pages/index.html
{% extends "base_site.html" %}

{% block title %}Pages{% endblock %}

{% block content %}
  <div class="">
    <div class="page-title">
      <div>
        <div class="" role="tabpanel">
          <ul class="nav nav-tabs bar_tabs left" role="tablist">
            <li role="presentation" class="active"><a href="#tab_all" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">All</a>
            </li>
            <li role="presentation" class=""><a href="#tab_recently_modified" role="tab" data-toggle="tab" aria-controls="Recently Modified" aria-expanded="false">Recently Modified</a>
            </li>
            <li role="presentation" class=""><a href="#tab_recently_viewed" role="tab" data-toggle="tab" aria-controls="Recently Viewed" aria-expanded="false">Recently Viewed</a>
            </li>
            <li role="presentation" class=""><a href="#tab_pinned" role="tab" data-toggle="tab" aria-controls="Favourited" aria-expanded="false">Pinned</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="tab-content">
        {% include "pages/tab.html" with list=object_list tab_id="tab_all" tab_aria_label="all-tab" active=True %}
        {% include "pages/tab.html" with list=recently_modified tab_id="tab_recently_modified" tab_aria_label="recently-modified-tab" %}
        {% include "pages/tab.html" with list=object_list tab_id="tab_recently_viewed" tab_aria_label="recently-viewed-tab" %}
        {% include "pages/tab.html" with list=object_list tab_id="tab_pinned" tab_aria_label="pinned-tab" %}
      </div>
    </div>
  </div>
{% endblock %}

templates/pages/page.html
{% extends "base_site.html" %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3></h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
              <h2>
                {{ object.title }}
              </h2>
              <div class="btn-group pull-right">
                <a href="#">
                  <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Trash">
                    <i class="fa fa-trash"></i>
                  </button>
                </a>
                <a href="#">
                  <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Print">
                    <i class="fa fa-print"></i>
                  </button>
                </a>
                <a href="#">
                  <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Tag">
                    <i class="fa fa-tag"></i>
                  </button>
                </a>
                <a href="{% url 'pages:edit' slug=object.slug %}">
                  <button class="btn btn-sm btn-primary">
                    <i class="fa fa-edit"></i> Edit
                  </button>
                </a>
              </div>

              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              {{ object.content | safe }}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/page_create.html
{% extends "base_site.html" %}

{% block title %}New Page{% endblock title %}

{% block javascripts %}
  {{ block.super }}
  {{ form.media }}
{% endblock %}

{% block content %}
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Create a new page</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <form method="POST">
            {% csrf_token %}
            <div class="x_title">
              <div class="form-group">
                {{ form.title.errors }}
                {{ form.title }}
              </div>
            </div>
            <div class="x_content">
              <div class="form-group textarea_primary">
                {{ form.content.errors }}
                {{ form.content }}
              </div>
              <div class="clearfix"></div>
              <div class="form-group">
                <input type="submit" class="btn btn-default submit pull-right" value="Create" />
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/page_form.html
{% extends "base_site.html" %}

{% block title %}New Page{% endblock title %}

{% block javascripts %}
  {{ block.super }}
  {{ form.media }}
{% endblock %}

{% block content %}
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Create a new page</h3>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <form method="POST">
            {% csrf_token %}
            <div class="x_title">
              <div class="form-group">
                {{ form.title.errors }}
                {{ form.title }}
              </div>
            </div>
            <div class="x_content">
              <div class="form-group textarea_primary">
                {{ form.content.errors }}
                {{ form.content }}
              </div>
              <div class="clearfix"></div>
              <div class="form-group">
                <input type="submit" class="btn btn-default submit pull-right" value="Save" />
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/page_index.html
{% extends "base_site.html" %}

{% block content %}
  <div class="">
    <div class="page-title">
      <div class="col-md-8 col-sm-6">
        <div class="" role="tabpanel">
          <ul class="nav nav-tabs bar_tabs left" role="tablist">
            <li role="presentation" class="active"><a href="#tab_all" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">All</a>
            </li>
            <li role="presentation" class=""><a href="#tab_recently_modified" role="tab" data-toggle="tab" aria-controls="Recently Modified" aria-expanded="false">Recently Modified</a>
            </li>
            <li role="presentation" class=""><a href="#tab_recently_viewed" role="tab" data-toggle="tab" aria-controls="Recently Viewed" aria-expanded="false">Recently Viewed</a>
            </li>
            <li role="presentation" class=""><a href="#tab_pinned" role="tab" data-toggle="tab" aria-controls="Favourited" aria-expanded="false">Pinned</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-4 col-sm-6">
        <div class="form-group top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button"><span><i class="fa fa-search"></i></span></button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="tab-content">
        <div id="tab_all" class="tab-pane fade active in" aria-labelledby="all-tab">
          <div class="x_panel">
            <div class="x_title">
              <h2></h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Last Modified</th>
                    <th>Author</th>
                  </tr>
                </thead>
                <tbody>

                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div id="tab_recently_modified" class="tab-pane fade" aria-labelledby="recently-modified-tab">
          <div class="x_panel">
            <div class="x_title">
              <h2></h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Last Modified</th>
                    <th>Author</th>
                  </tr>
                </thead>
                <tbody>

                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div id="tab_recently_viewed" class="tab-pane fade" aria-labelledby="recently-viewed-tab">
          <div class="x_panel">
            <div class="x_title">
              <h2></h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Last Modified</th>
                    <th>Author</th>
                  </tr>
                </thead>
                <tbody>

                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div id="tab_pinned" class="tab-pane fade" aria-labelledby="pinned-tab">
          <div class="x_panel">
            <div class="x_title">
              <h2></h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Last Modified</th>
                    <th>Author</th>
                  </tr>
                </thead>
                <tbody>

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/pages/tab.html
{% load category_label %}
{% block tab %}
  <div id="{{ tab_id }}" class="tab-pane fade {% if active %}active in{% endif %}" aria-labelledby="{{ tab_aria_label }}">
    <div class="x_panel">
      <div class="x_content">
        <table class="table">
          <thead>
            <tr>
              <th class="col-xs-1">Category</th>
              <th class="col-xs-8">Title</th>
              <th class="col-xs-1">Creator</th>
              <th class="col-xs-2">Last Modified</th>
            </tr>
          </thead>
          <tbody>
            {% for page in list %}
              <tr>
                <td>
                  <span class="label {{ page|label }} center-block">{{ page.category }}</span>
                </td>
                <td>
                  <a href="{{ page.get_absolute_url }}">{{ page.title }}</a>
                </td>
                <td>
                  {{ page.creator }}
                </td>
                <td>
                  {{ page.creation_date }}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}