authentication/urls.py
from django.conf.urls import url
from .views import SignInView, SignOutView, SignUpView

urlpatterns = [
    url(
        regex=r'^signin/?$',
        view=SignInView.as_view(),
        name='signin'
    ),
    url(
        regex=r'^signout/?$',
        view=SignOutView.as_view(),
        name='signout'
    ),
    url(
        regex=r'^signup/?$',
        view=SignUpView.as_view(),
        name='signup'
    ),
]

dashboard/urls.py
from django.conf.urls import url
from .views import DashboardView

urlpatterns = [
    url(
        regex=r'^$',
        view=DashboardView.as_view(),
        name='dashboard'
    )
]

events/urls.py
from django.conf.urls import url
from .views import (
    EventCalendarView,
    EventCreateView,
    EventDetailView,
    EventUpdateView,
    EventHistoryView,
    EventIndexView
)

urlpatterns = [
    url(
        regex=r'^calendar/?$',
        view=EventCalendarView.as_view(),
        name='calendar'
    ),
    url(
        regex=r'^create/?$',
        view=EventCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/update/?$',
        view=EventUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/history/?$',
        view=EventHistoryView.as_view(),
        name='history'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/?$',
        view=EventDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'',
        view=EventIndexView.as_view(),
        name='index'
    ),
]

orbit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from avatar import urls as avatar

local_patterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('authentication.urls', namespace='authentication')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^event/', include('events.urls', namespace='events')),
    url(r'^page/', include('pages.urls', namespace='pages')),
    url(r'^project/', include('projects.urls', namespace='projects')),
]

third_party_patterns = [
    url(r'^avatar/', include(avatar)),
]

urlpatterns = local_patterns + third_party_patterns


def fourohfour(request):
    return render(request, '404.html', status=404)


handler404 = fourohfour

pages/urls.py
from django.conf.urls import url
from .views import PageDetailView, PageCreateView, PageUpdateView, PageHistoryView, PageIndexView

urlpatterns = [
    url(
        regex=r'^create/?$',
        view=PageCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/update/?$',
        view=PageUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/history/?$',
        view=PageHistoryView.as_view(),
        name='history'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/?$',
        view=PageDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'',
        view=PageIndexView.as_view(),
        name='index'
    ),
]

templates/base_site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}
      <title>Orbit | {% block title %}{% endblock title %}</title>
      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <!-- Avatar Colours -->
        <link href="{% static 'orbit/css/avatar-colours.css' %}" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="{% static 'orbit/css/custom.css' %}" rel="stylesheet">
    {% endblock head %}
  </head>
  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">
          {% block sidebar %}
          <div class="col-md-3 left_col
            {% block sidebar_class %}{% endblock sidebar_class %} menu_fixed">
            {% include "sidebar.html" %}
          </div>
          {% endblock sidebar %}
          {% block top_navigation %}
            <div class="top_nav">
              {% include "top_navigation.html" %}
            </div>
          {% endblock top_navigation %}
          {% block content_container %}
            <div class="right_col" role="main">
              {% block content %}{% endblock content %}
            </div>
          {% endblock content_container %}
          {% block footer %}
            {% include "footer.html" %}
          {% endblock footer %}
        </div>
      </div>
      {% block javascripts %}
        <!-- jQuery -->
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="{% static 'orbit/js/custom.js' %}"></script>
    {% endblock body %}
  </body>
</html>

templates/footer.html
<footer>
  <div class="col-sm-7 col-xs-12">
    <div>About</div>
    <div>Contact</div>
    <div>FAQs</div>
    <div>Privacy Policy</div>
    <div>Terms of Service</div>
  </div>
  <div class="col-sm-5 col-xs-12">
    <div class="col-xs-12">
      <div class="pull-right">
        <h1>
          <i class="fa fa-facebook-square"></i>
          <i class="fa fa-twitter-square"></i>
          <i class="fa fa-google-plus-square"></i>
          <i class="fa fa-youtube-square"></i>
        </h1>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="pull-right">
        <span>
          Orbit - A Content Management System for <a href="http://www.youthaction.org.au/outburst">Outburst!</a>
        </span>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="pull-right">
        <i class="fa fa-copyright"></i> {% now "Y" %} <a href="http://www.youthaction.org.au">Youth Action</a>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
</footer>

templates/sidebar.html
{% load static %}
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'dashboard:dashboard' %}" class="site_title">
      <img class="site_brand" src="{% static 'orbit/img/orbit_icon.svg' %}"/>
      <span>Orbit</span>
    </a>
  </div>

  <div class="clearfix"></div>

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <ul class="nav side-menu">
        <li>
          <a href="{% url 'dashboard:dashboard' %}">
            <span><i class="fa fa-home"></i></span>
            <span>Dashboard</span>
          </a>
        </li>
        <li>
          <a href="{% url 'events:index' %}">
            <span><i class="fa fa-group"></i></span>
            <span>Events</span>
          </a>
        </li>
        <li>
          <a href="{% url 'pages:index' %}">
            <span><i class="fa fa-file-text"></i></span>
            <span>Pages</span>
          </a>
        </li>
        <li>
          <a href="{% url 'events:calendar' %}">
            <span><i class="fa fa-calendar"></i></span>
            <span>Calendar</span>
          </a>
        </li>
        <li>
          <a href="{% url 'projects:index' %}">
            <span><i class="fa fa-clipboard"></i></span>
            <span>Projects</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">

  </div>
  <!-- /menu footer buttons -->
</div>

templates/top_navigation.html
{% load avatar_tag %}
{% load guardian_tags %}
<div class="nav_menu">
  <nav>
    <div class="col-xs-1">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>
    </div>
    <div class="col-xs-11">
      <ul class="nav navbar-nav navbar-right">
          <li>
            <a class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              <span>{% avatar user 30 %}</span>
              <span class="fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
              <li>
                <a href="{{ user.get_absolute_url }}">
                  <span>Profile</span>
                  <span><i class="fa fa-user pull-right"></i></span>
                </a>
              </li>
              <li>
                <a>
                  <span>Messages</span>
                  <span><i class="fa fa-envelope-o pull-right"></i></span>
                </a>
              </li>
              <li>
                <a href="javascript:;">
                  <span>Settings</span>
                  <span><i class="fa fa-gear pull-right"></i></span>
                </a>
              </li>
              {% if request.user.is_staff %}
                <li>
                  <a href="admin">
                    <span>Admin</span>
                    <span><i class="fa fa-gears pull-right"></i></span>
                  </a>
                </li>
              {% endif %}
              <li>
                <a href="javascript:;">
                  <span>Help</span>
                  <span><i class="fa fa-question-circle pull-right"></i></span>
                </a>
              </li>
              <li>
                <a href="{% url 'authentication:signout' %}">
                  <span>Log Out</span>
                  <span><i class="fa fa-sign-out pull-right"></i></span>
                 </a>
               </li>
            </ul>
          </li>
          <li>
            <div class="btn-group">
            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle navbar-btn" type="button" aria-expanded="false">
              <span>Create </span>
              <span class="caret"></span>
            </button>
            <ul role="menu" class="dropdown-menu">
              <li>
                <a href="{% url 'events:create' %}">
                  <span>Event</span>
                  <span><i class="fa fa-group pull-right"></i></span>
                </a>
              </li>
              <li>
                <a href="{% url 'pages:create' %}">
                  <span>Page</span>
                  <span><i class="fa fa-file-text-o pull-right"></i></span>
                </a>
              </li>
              <li>
                <a href="{% url 'projects:create' %}">
                  <span>Project</span>
                  <span><i class="fa fa-clipboard pull-right"></i></span>
                </a>
              </li>
            </ul>
          </li>
          <li class="col-xs-5 col-sm-9">
            <div class="top_search input-group">
              <input class="form-control" placeholder="Search for..." />
              <span class="input-group-btn">
                <button class="btn btn-default" type="button"><span><i class="fa fa-search"></i></span></button>
              </span>
            </div>
          </li>
        </div>
      </ul>
    </div>
  </nav>
</div>