events/urls.py
from django.conf.urls import url
from .views import (
    EventCalendarView,
    EventCreateView,
    EventDetailView,
    EventUpdateView,
    EventHistoryView,
    EventIndexView
)

urlpatterns = [
    url(
        regex=r'^calendar/?$',
        view=EventCalendarView.as_view(),
        name='calendar'
    ),
    url(
        regex=r'^create/?$',
        view=EventCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/update/?$',
        view=EventUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/history/?$',
        view=EventHistoryView.as_view(),
        name='history'
    ),
    url(
        regex=r'^(?P<pk>[^/]+)/?$',
        view=EventDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'',
        view=EventIndexView.as_view(),
        name='index'
    ),
]

orbit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import render
from avatar import urls as avatar

local_patterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('authentication.urls', namespace='authentication')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^event/', include('events.urls', namespace='events')),
    url(r'^page/', include('pages.urls', namespace='pages')),
    url(r'^project/', include('projects.urls', namespace='projects')),
]

third_party_patterns = [
    url(r'^avatar/', include(avatar)),
]

urlpatterns = local_patterns + third_party_patterns


def fourohfour(request):
    return render(request, '404.html', status=404)


handler404 = fourohfour

events/models.py
from django.db import models
from django.urls import reverse
from django.utils.timesince import timesince
from model_utils.models import TimeFramedModel
from pages.models import BasePage


class Event(BasePage, TimeFramedModel):
    start = models.DateTimeField()
    end = models.DateTimeField()
    # attendance = models.ManyToManyField(Account)

    # TODO ensure start is before end

    @property
    def duration(self):
        return timesince(d=self.start, now=self.end)

    @property
    def display_date_range(self):
        if self.start.month == self.end.month and self.start.day == self.end.day:
            return self.start.strftime('%d %b')
        else:
            return self.start.strftime('%d %b') + ' - ' + self.end.strftime('%d %b')

    @property
    def display_date_time_range(self):
        return self.start.strftime('%Y, %b %d, %I:%M%p') + ' - ' + self.end.strftime('%Y, %b %d, %I:%M%p')

    def get_absolute_url(self):
        return reverse('events:detail', kwargs={'pk': self.pk})

    def get_absolute_history_url(self):
        return reverse('events:history', kwargs={'pk': self.pk})

events/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from pages.forms import PageForm
from .models import Event


class EventForm(PageForm):

    class Meta(PageForm.Meta):
        model = Event
        fields = PageForm.Meta.fields + ['start', 'end']
        widgets = PageForm.Meta.widgets.copy()
        widgets.update({
            'start': forms.DateInput(attrs={
                'class': 'form-control',
                'placeholder': 'Start',
            }),
            'end': forms.DateInput(attrs={
                'class': 'form-control',
                'placeholder': 'End',
            }),
        })

events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import ListView, TemplateView
from .forms import EventForm
from .models import Event
from pages.views import PageCreateView, PageDetailView, PageHistoryView, PageUpdateView


class EventCalendarView(LoginRequiredMixin, TemplateView):
    template_name = 'events/calendar.html'
    model = Event

    def get_context_data(self, *args, **kwargs):
        context = super(EventCalendarView, self).get_context_data(*args, **kwargs)
        return context


class EventCreateView(PageCreateView):
    template_name = 'events/form.html'
    model = Event
    form_class = EventForm


class EventDetailView(PageDetailView):
    template_name = 'events/detail.html'
    model = Event

    def render_to_response(self, context, **response_kwargs):
        response = super(EventDetailView, self).render_to_response(context, **response_kwargs)
        return response

    def as_view(self, cls, **initkwargs):
        view = super(EventDetailView, self).as_view(cls, **initkwargs)
        return view


class EventHistoryView(PageHistoryView):
    model = Event


class EventIndexView(LoginRequiredMixin, ListView):
    template_name = 'events/index.html'
    model = Event
    queryset = Event.objects.filter(is_removed=False)
    ordering = ['-creation_date']


class EventUpdateView(PageUpdateView):
    template_name = 'events/form.html'
    model = Event
    form_class = EventForm

templates/events/calendar.html
{% extends "base_site.html" %}

{% block title %}Calendar{% endblock %}

{% block content %}

{% endblock %}

templates/events/detail.html
{% extends "base_site.html" %}
{% load static %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
  <div class="row">
    <div class="x_panel">
      <div class="x_title">
        <div>
          <h2>{{ object.title }}</h2>
        </div>
        <div class="btn-group pull-right">
          <a href="#">
            <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Trash">
              <i class="fa fa-trash"></i>
            </button>
          </a>
          <a href="#">
            <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Print">
              <i class="fa fa-print"></i>
            </button>
          </a>
          <a href="{{ object.get_absolute_history_url }}">
            <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="History">
              <i class="fa fa-history"></i>
            </button>
          </a>
          <a href="#">
            <button class="btn btn-sm btn-default" type="button"  data-placement="top" data-toggle="tooltip" data-original-title="Tag">
              <i class="fa fa-tag"></i>
            </button>
          </a>
          {% if object.is_removed %}
            <a>
              <button class="btn btn-sm btn-primary disabled">
                <i class="fa fa-edit"></i> Update
              </button>
            </a>
          {% else %}
            <a href="{% url 'events:update' pk=object.pk %}">
              <button class="btn btn-sm btn-primary">
                <i class="fa fa-edit"></i> Update
              </button>
            </a>
          {% endif %}
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="pull-right">
          <h4>
            <span class="label label-info" type="button"  data-placement="left" data-toggle="tooltip" data-original-title="{{ object.duration }} long">{{ object.display_date_time_range }}</span>
          </h4>
        </div>
        {{ object.content | safe }}
      </div>
    </div>
  </div>
{% endblock %}

templates/events/form.html
{% extends "base_site.html" %}
{% load static %}

{% block title %}
  {% if form.instance.id %}
    Edit Event
  {% else %}
    New Event
  {% endif %}
{% endblock %}

{% block stylesheets %}
  {{ block.super }}
  <!-- bootstrap-daterangepicker -->
  <link href="{% static 'bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css' %}" rel="stylesheet"/>
{% endblock %}

{% block javascripts %}
  {{ block.super }}
  <script src="{% static 'moment/moment.js' %}"></script>
  <script src="{% static 'bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
  <script src="{% static 'orbit/js/events/event_form.js' %}"></script>
  {{ form.media }}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        {{ form.errors }}
        {% for error in form.non_field_errors %}
          <div class="alert alert-error" role="alert">
            {{ error }}
          </div>
        {% endfor %}
        <form method="POST">
          {{ form.errors }}
          {% csrf_token %}
          <div class="col-sm-3 col-xs-12">
            <div class="col-sm-12 col-xs-6">
              <div class="form-group {% if form.start.errors %}has-error{% endif %}">
                <div class="input-group date center-block" id="startDateTimePicker">
                  {% if form.start.errors %}
                    <label class="control-label" for="{{ form.start.auto_id }}">{{ form.start.errors.as_text|cut:"* "}}</label>
                  {% endif %}
                  {{ form.start }}
                </div>
              </div>
            </div>
            <div class="col-sm-12 col-xs-6">
              <div class="form-group {% if form.end.errors %}has-error{% endif %}">
                <div class="input-group date center-block" id="endDateTimePicker">
                  {% if form.end.errors %}
                    <label class="control-label" for="{{ form.end.auto_id }}">{{ form.end.errors.as_text|cut:"* "}}</label>
                  {% endif %}
                  {{ form.end }}
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-9 col-xs-12">
            <div class="form-group {% if form.title.errors %}has-error{% endif %}">
              {% if form.title.errors %}
                <label class="control-label" for="{{ form.title.auto_id }}">{{ form.title.errors.as_text|cut:"* "}}</label>
              {% endif %}
              {{ form.title }}
            </div>
            <div class="form-group textarea-primary {% if form.content.errors %}has-error{% endif %}">
              {% if form.content.errors %}
                <label class="control-label" for="{{ form.content.auto_id }}">{{ form.content.errors.as_text|cut:"* "}}</label>
              {% endif %}
              {{ form.content }}
            </div>
            <div class="form-group">
              <div class="input-group">
                {{ form.changelog }}
                <span class="input-group-btn">
                  <input type="submit" class="btn btn-default submit btn-unpad" value="Save"/>
                </span>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/events/index.html
{% extends "base_site.html" %}
{% load timediff_filter %}

{% block title %}Events{% endblock %}

{% block content %}
  <div class="">
    <div class="row">
      <div class="x_panel">
        <table class="table">
          <thead>
            <tr>
              <th class="col-xs-3 col-sm-2 text-center">
                <span>
                  <i class="fa fa-calendar" data-placement="top" data-toggle="tooltip" data-original-title="Date"></i>
                </span>
              </th>
              <th class="col-xs-7 col-sm-8">
                <span>
                  Event
                </span>
              </th>
              <th class="col-xs-1 text-center">
                <span>
                  <i class="fa fa-file-text" data-placement="top" data-toggle="tooltip" data-original-title="Notes"></i>
                </span>
              </th>
              <th class="col-xs-1 text-center">
                <span>
                  <i class="fa fa-user" data-placement="top" data-toggle="tooltip" data-original-title="Attendance"></i>
                </span>
              </th>
            </tr>
          </thead>
          <tbody>
            {% for event in object_list %}
              <tr>
                <td>
                  <div class="text-center" data-placement="left" data-toggle="tooltip" data-original-title="{{ event.end|timediff }}">{{ event.display_date_range }}</div>
                </td>
                <td>
                  <div><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></div>
                </td>
                <td class="text-center">
                  <div>
                    <i class="fa fa-file-text-o"></i>
                  </div>
                </td>
                <td class="text-center">
                  <div>1/24</div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}